//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvikLimbasiya_0415.Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite_items
    {
        public int favorite_id { get; set; }
        public int userId { get; set; }
        public int BikeId { get; set; }
        public Nullable<System.DateTime> date_favorited { get; set; }
    
        public virtual BikeDetails BikeDetails { get; set; }
        public virtual RegisterRide RegisterRide { get; set; }
    }
}
