//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvikLimbasiya_0415.Model.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DhruvikLimbasiya_0415Entities : DbContext
    {
        public DhruvikLimbasiya_0415Entities()
            : base("name=DhruvikLimbasiya_0415Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<RegisterRide> RegisterRide { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ZipCode> ZipCode { get; set; }
        public virtual DbSet<BikeDetails> BikeDetails { get; set; }
        public virtual DbSet<favorite_items> favorite_items { get; set; }
    }
}
