//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvikLimbasiya_0415.Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterRide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterRide()
        {
            this.favorite_items = new HashSet<favorite_items>();
        }
    
        public int userId { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string AddressLineTwo { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> zipCode { get; set; }
        public string profilePhoto { get; set; }
        public string password { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual State State1 { get; set; }
        public virtual ZipCode ZipCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite_items> favorite_items { get; set; }
    }
}
